name: particle_fx
description: A high-performance Flutter particle effects engine for image particles, emitters, forces, trails, presets, weighted textures, and layered effects.
version: 0.1.2
repository: https://github.com/xxmushroom/particle_fx
issue_tracker: https://github.com/xxmushroom/particle_fx/issues

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0